version: '3'
services:
    rasa:
      container_name: "chatbot_purple"
      user: root
      build: 
        context: ./rasa
      volumes:
        - "./rasa:/app"
      ports: 
        - "10010:5005"
    action_server:
      container_name: "action_server_purple"
      build: 
        context: ./rasa/actions
      volumes:
        - ./rasa:/app/actions
        - ./rasa:/app/data
      ports:
        - 10011:5055